require 'aws-sdk-s3'

# Description: Sublayer::Action responsible for uploading a file to an AWS S3 bucket.
# This action facilitates the automation of data storage and backup to S3,
# a scalable storage service in the cloud.
#
# It is initialized with an S3 bucket name, file path, and the target key in the bucket.
# It returns the public URL of the uploaded file.
#
# Example usage: When you want to back up files generated by AI processes or LLMs to S3.

class AwsS3UploadFileAction < Sublayer::Actions::Base
  def initialize(bucket_name:, file_path:, key:)
    @bucket_name = bucket_name
    @file_path = file_path
    @key = key
    @client = Aws::S3::Client.new(region: ENV['AWS_REGION'])
  end

  def call
    begin
      upload_file_to_s3
      public_url
    rescue Aws::S3::Errors::ServiceError => e
      error_message = "Error uploading file to S3: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end

  private

  def upload_file_to_s3
    @client.put_object(
      bucket: @bucket_name,
      key: @key,
      body: File.open(@file_path, 'rb')
    )
    Sublayer.configuration.logger.log(:info, "Successfully uploaded file to S3 bucket: #{@bucket_name}, key: #{@key}")
  end

  def public_url
    "https://#{@bucket_name}.s3.amazonaws.com/#{@key}"
  end
end