require 'httparty'
require 'json'

# Description: Sublayer::Action responsible for triggering a Zapier Zap.
# This action allows Sublayer to integrate with thousands of other services via Zapier.
#
# It is initialized with the Zap ID and a data payload.
# It returns the HTTP response from Zapier.
#
# Example usage: When you want to trigger a Zapier workflow from within a Sublayer process,
# passing data generated by an LLM to another service via Zapier.

class ZapierTriggerZapAction < Sublayer::Actions::Base
  include HTTParty
  format :json

  def initialize(zap_id:, data: {})
    @zap_id = zap_id
    @data = data
    @webhook_url = "https://hooks.zapier.com/hooks/catch/#{@zap_id}/"
  end

  def call
    begin
      response = self.class.post(@webhook_url, body: @data.to_json, headers: { 'Content-Type' => 'application/json' })

      if response.success?
        Sublayer.configuration.logger.log(:info, "Zapier Zap with ID \#{@zap_id} triggered successfully.")
        response
      else
        error_message = "Failed to trigger Zapier Zap with ID \#{@zap_id}: HTTP \#{response.code} - \#{response.message} - \#{response.body}"
        Sublayer.configuration.logger.log(:error, error_message)
        raise StandardError, error_message
      end
    rescue HTTParty::Error => e
      error_message = "HTTP error triggering Zapier Zap: \#{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    rescue StandardError => e
      error_message = "Error triggering Zapier Zap: \#{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise e
    end
  end
end