require 'pinecone'

# Description: Sublayer::Action responsible for upserting a vector embedding into a Pinecone vector database.
# This action allows for storing and retrieving embeddings generated by AI models for semantic search or similarity analysis.
#
# It is initialized with pinecone_index_name, id, vector, and optional namespace.
# It returns the id of the upserted vector.
#
# Example usage: When you want to store embeddings generated by an AI model into a Pinecone index for semantic search.

class PineconeUpsertVectorAction < Sublayer::Actions::Base
  def initialize(pinecone_index_name:, id:, vector:, namespace: nil)
    @pinecone_index_name = pinecone_index_name
    @id = id
    @vector = vector
    @namespace = namespace
    Pinecone.configure do |config|
      config.api_key = ENV['PINECONE_API_KEY']
      config.environment = ENV['PINECONE_ENVIRONMENT'] # Example: 'us-east1-aws'
    end

    @index = Pinecone::Index.new(@pinecone_index_name)
  end

  def call
    begin
      upsert_vector
      Sublayer.configuration.logger.log(:info, "Successfully upserted vector with id \#{@id} to Pinecone index \#{@pinecone_index_name}")
      @id
    rescue Pinecone::Error => e
      error_message = "Error upserting vector to Pinecone: \#{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    rescue StandardError => e
      error_message = "Error upserting vector to Pinecone: \#{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise e
    end
  end

  private

  def upsert_vector
    vectors = [
      {
        id: @id,
        values: @vector,
        metadata: {}
      }
    ]

    @index.upsert(
      vectors: vectors, 
      namespace: @namespace
    )
  end
end