require 'sendgrid-ruby'

# Description: Sublayer::Action responsible for sending emails using the SendGrid API.
# This action allows for easy integration of email sending capabilities into Sublayer workflows,
# enabling automated communication or notifications based on AI-driven processes.
#
# Requires: 'sendgrid-ruby' gem
# $ gem install sendgrid-ruby
# Or add `gem 'sendgrid-ruby'` to your Gemfile
#
# It is initialized with recipient email, subject, and content.
# Optionally, you can provide a sender email (falls back to ENV['SENDGRID_FROM_EMAIL']).
# It returns the SendGrid API response to confirm the email was sent successfully.
#
# Example usage: When you want to send an email notification or report generated by an AI process.

class SendgridEmailSendAction < Sublayer::Actions::Base
  def initialize(to:, subject:, content:, from: nil)
    @to = to
    @subject = subject
    @content = content
    @from = from || ENV['SENDGRID_FROM_EMAIL']
    @api_key = ENV['SENDGRID_API_KEY']
  end

  def call
    begin
      response = send_email
      Sublayer.configuration.logger.log(:info, "Email sent successfully to #{@to}")
      response
    rescue SendGrid::Exception => e
      error_message = "Error sending email via SendGrid: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end

  private

  def send_email
    sg = SendGrid::API.new(api_key: @api_key)
    
    mail = SendGrid::Mail.new(
      SendGrid::Email.new(email: @from),
      @subject,
      SendGrid::Email.new(email: @to),
      SendGrid::Content.new(type: 'text/plain', value: @content)
    )

    sg.client.mail._('send').post(request_body: mail.to_json)
  end
end
