require 'sendgrid-ruby'

# Description: Sublayer::Action responsible for sending an email using SendGrid.
# It is initialized with to_email, from_email, subject, and body.
# It returns the HTTP status code to confirm the email was sent successfully.
#
# Example usage: When you want to send notifications or reports generated by AI agents.

class SendgridSendEmailAction < Sublayer::Actions::Base
  include SendGrid

  def initialize(to_email:, from_email:, subject:, body:)
    @to_email = to_email
    @from_email = from_email
    @subject = subject
    @body = body
    @api_key = ENV['SENDGRID_API_KEY']
  end

  def call
    from = Email.new(email: @from_email)
    to = Email.new(email: @to_email)
    content = Content.new(type: 'text/plain', value: @body)
    mail = Mail.new(from, @subject, to, content)

    sg = SendGrid::API.new(api_key: @api_key)
    begin
      response = sg.client.mail._('send').post(request_body: mail.to_json)
      Sublayer.configuration.logger.log(:info, "Email sent successfully to #{@to_email}")
      response.status_code.to_i
    rescue StandardError => e
      error_message = "Error sending email: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end
end
