require 'sendgrid-ruby'
include SendGrid

# Description: Sublayer::Action responsible for sending an email using SendGrid.
# This action allows for sending notifications or reports generated by AI agents.
#
# Requires: 'sendgrid-ruby' gem
# $ gem install sendgrid-ruby
# Or add `gem 'sendgrid-ruby'` to your Gemfile
#
# It is initialized with recipient, sender, subject, and body (plain text or HTML).
# It returns the HTTP status code to confirm it was sent successfully.
#
# Example usage: When you want to send a notification or report from an AI process via email.

class SendgridSendEmailAction < Sublayer::Actions::Base
  def initialize(recipient:, sender:, subject:, body:)
    @recipient = recipient
    @sender = sender
    @subject = subject
    @body = body
    @api_key = ENV['SENDGRID_API_KEY']
  end

  def call
    begin
      from = Email.new(email: @sender)
      to = Email.new(email: @recipient)
      subject = @subject
      content = Content.new(type: 'text/plain', value: @body)
      mail = Mail.new(from, subject, to, content)

      sg = SendGrid::API.new(api_key: @api_key)
      response = sg.client.mail._('send').post(request_body: mail.to_json)

      Sublayer.configuration.logger.log(:info, "Email sent successfully to #{@recipient} with status code: #{response.status_code}")
      response.status_code.to_i
    rescue SendGrid::Exception => e
      error_message = "Error sending SendGrid email: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    rescue StandardError => e
        error_message = "Error: #{e.message}"
        Sublayer.configuration.logger.log(:error, error_message)
        raise StandardError, error_message
    end
  end
end