require 'sendgrid-ruby'

# Description: Sublayer::Action responsible for sending an email via SendGrid.
# Useful for sending notifications or reports generated by AI processes.
#
# Requires: sendgrid-ruby gem.
# $ gem install sendgrid-ruby
#
# It is initialized with a to, from, subject, and content.
# It returns the response from the SendGrid API.
#
# Example usage: When you want to send a notification or report generated by an AI process via email.

class SendgridSendEmailAction < Sublayer::Actions::Base
  def initialize(to:, from:, subject:, content:)
    @to = to
    @from = from
    @subject = subject
    @content = content
    @api_key = ENV['SENDGRID_API_KEY']
  end

  def call
    begin
      send_email
    rescue StandardError => e
      error_message = "Error sending email via SendGrid: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end

  private

  def send_email
    sg = SendGrid::API.new(api_key: @api_key)
    from = SendGrid::Email.new(email: @from)
    to = SendGrid::Email.new(email: @to)
    subject = @subject
    content = SendGrid::Content.new(type: 'text/plain', value: @content)
    mail = SendGrid::Mail.new(from, subject, to, content)

    response = sg.client.mail._('send').post(request_body: mail.to_json)

    if response.status_code.to_i >= 200 && response.status_code.to_i < 300
      Sublayer.configuration.logger.log(:info, "Email sent successfully to #{@to} via SendGrid")
    else
      error_message = "Failed to send email via SendGrid. Status code: #{response.status_code}, Body: #{response.body}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end

    response
  end
end