# Description: Sublayer::Action responsible for sending an email using a specified email provider.
# Currently supports SendGrid. Requires API key, sender email, recipient email, subject, and body.
# Useful for sending notifications, summaries, or reports generated by AI models.
#
# Example usage: When you want to send an email notification after an AI model completes a task.

require 'sendgrid-ruby'
include SendGrid

class EmailSendAction < Sublayer::Actions::Base
  def initialize(api_key:, sender_email:, recipient_email:, subject:, body:)
    @api_key = api_key
    @sender_email = sender_email
    @recipient_email = recipient_email
    @subject = subject
    @body = body
  end

  def call
    from = Email.new(email: @sender_email)
    to = Email.new(email: @recipient_email)
    content = Content.new(type: 'text/plain', value: @body)
    mail = Mail.new(from, @subject, to, content)

    sg = SendGrid::API.new(api_key: @api_key)
    begin
      response = sg.client.mail._('send').post(request_body: mail.to_json)
      Sublayer.configuration.logger.log(:info, "Email sent successfully to #{@recipient_email}")
      response.status_code
    rescue Exception => e
      error_message = "Error sending email: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end
end
