require 'net/smtp'

# Description: Sublayer::Action responsible for sending email notifications with
# customizable messages and attachments.
# This action is useful for delivering results or alerts generated from AI processes via email.
#
# Example usage: When you want to send a report or an alert generated by AI to a set of recipients.

class EmailNotificationAction < Sublayer::Actions::Base
  def initialize(smtp_details:, from:, to:, subject:, message:, attachments: [])
    @smtp_details = smtp_details # { address, port, domain, user_name, password, authentication, enable_starttls_auto }
    @from = from
    @to = to
    @subject = subject
    @message = message
    @attachments = attachments
  end

  def call
    begin
      send_email
      Sublayer.configuration.logger.log(:info, "Email sent successfully to #{@to}")
    rescue StandardError => e
      error_message = "Error sending email: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end

  private

  def send_email
    mail_content = build_mail_content
    Net::SMTP.start(@smtp_details[:address], @smtp_details[:port],
                    @smtp_details[:domain], @smtp_details[:user_name],
                    @smtp_details[:password], @smtp_details[:authentication]) do |smtp|
      smtp.send_message(mail_content, @from, @to)
    end
  end

  def build_mail_content
    # Build the email headers
    headers = []
    headers << "From: #{@from}"
    headers << "To: #{@to}"
    headers << "Subject: #{@subject}"
    headers << "MIME-Version: 1.0"
    headers << "Content-Type: multipart/mixed; boundary=unique-boundary-1"
    
    # Build the body with attachments
    body = []
    body << "--unique-boundary-1"
    body << "Content-Type: text/plain; charset=UTF-8"
    body << "Content-Transfer-Encoding:7bit"
    body << ""
    body << @message
    
    # Add attachments if any
    @attachments.each do |attachment|
      content = File.read(attachment[:path])
      encoded_content = [content].pack('m')
      body << "--unique-boundary-1"
      body << "Content-Type: #{attachment[:mime_type]}; name=\"#{attachment[:name]}\""
      body << "Content-Transfer-Encoding: base64"
      body << "Content-Disposition: attachment; filename=\"#{attachment[:name]}\""
      body << ""
      body << encoded_content
    end

    # Closing boundary
    body << "--unique-boundary-1--"
    
    # Combine headers and body
    [headers.join("\n"), body.join("\n")].join("\n\n")
  end
end
