require 'sendgrid-ruby'

# Description: Sublayer::Action responsible for sending emails using the SendGrid API.
# This action is intended to be used for sending LLM-generated emails, notifications, reports, etc.
#
# It is initialized with parameters like 'to', 'from', 'subject', and 'body'.
# It returns the SendGrid API response to confirm the email was sent successfully.
#
# Example usage: When you want to send a notification or report generated by an AI process via email.

class SendGridSendEmailAction < Sublayer::Actions::Base
  def initialize(to:, from:, subject:, body:, api_key: nil, **kwargs)
    @to = to
    @from = from
    @subject = subject
    @body = body
    @api_key = api_key || ENV['SENDGRID_API_KEY']
    @client = SendGrid::API.new(api_key: @api_key)
  end

  def call
    data = {
      personalizations: [
        {
          to: [{ email: @to }],
          subject: @subject
        }
      ],
      from: { email: @from },
      content: [
        {
          type: 'text/plain',
          value: @body
        }
      ]
    }

    begin
      response = @client.client.mail._('send').post(request_body: data)
      Sublayer.configuration.logger.log(:info, "Email sent successfully to #{@to} with response code: #{response.status_code}")
      response
    rescue Exception => e
      Sublayer.configuration.logger.log(:error, "Error sending email: #{e.message}")
      raise e
    end
  end
end