require 'google/apis/sheets_v4'
require 'googleauth'

# Description: Sublayer::Action responsible for appending data to a Google Sheet.
# This action facilitates automation in data collection and reporting workflows
# by allowing easy integration with Google Sheets.
#
# It is initialized with a spreadsheet_id, range, and values to append.
# It returns the response from the API to confirm successful append.
#
# Example usage: When you want to automate the process of recording data
# generated by an AI process into a Google Sheet for reporting or analysis.

class GoogleSheetsDataAppendAction < Sublayer::Actions::Base
  def initialize(spreadsheet_id:, range:, values:)
    @spreadsheet_id = spreadsheet_id
    @range = range
    @values = values
    @service = Google::Apis::SheetsV4::SheetsService.new
    @service.authorization = Google::Auth.get_application_default(["https://www.googleapis.com/auth/spreadsheets"])
  end

  def call
    append_values
  rescue Google::Apis::Error => e
    error_message = "Error appending data to Google Sheet: #{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise StandardError, error_message
  end

  private

  def append_values
    value_range_object = Google::Apis::SheetsV4::ValueRange.new(values: @values)
    response = @service.append_spreadsheet_value(
      @spreadsheet_id, 
      @range, 
      value_range_object, 
      value_input_option: 'RAW'
    )
    Sublayer.configuration.logger.log(:info, "Successfully appended data to spreadsheet ##{@spreadsheet_id}")
    response
  end
end
