require 'google/apis/drive_v3'
require 'googleauth'

# Description: Sublayer::Action responsible for uploading a file to a specified folder in Google Drive.
# This action allows integration with Google Drive, utilizing the Google Drive API to manage file uploads.
#
# It is initialized with a file path, drive folder ID, and an optional description.
# It returns the file ID of the uploaded file on Google Drive.
#
# Example usage: When you want to upload reports or documents generated by an AI process to Google Drive for easy access and sharing.

class GoogleDriveFileUploadAction < Sublayer::Actions::Base
  def initialize(file_path:, drive_folder_id:, description: nil)
    @file_path = file_path
    @drive_folder_id = drive_folder_id
    @description = description || 'Uploaded by Sublayer'
    @drive_service = Google::Apis::DriveV3::DriveService.new
    @drive_service.authorization = Google::Auth.get_application_default(["https://www.googleapis.com/auth/drive.file"])
  end

  def call
    upload_file_to_drive
  rescue Google::Apis::Error => e
    error_message = "Error uploading file to Google Drive: \\#{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise StandardError, error_message
  rescue StandardError => e
    error_message = "Unexpected error during Google Drive file upload: \\#{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise e
  end

  private

  def upload_file_to_drive
    file_metadata = {
      name: File.basename(@file_path),
      parents: [@drive_folder_id]
    }
    file = Google::Apis::DriveV3::File.new(file_metadata)

    result = @drive_service.create_file(
      file,
      upload_source: @file_path,
      content_type: MIME::Types.type_for(@file_path).first.to_s,
      fields: 'id, name'
    )

    Sublayer.configuration.logger.log(:info, "File '#{result.name}' uploaded successfully to Google Drive with ID: #{result.id}")
    result.id
  end
end
