# Description: Sublayer::Action for uploading files to Google Drive. This action allows
# integration with Google Drive, enabling automatic upload of files such as
# generated reports or data to cloud storage for collaboration and backup.
#
# Requires: 'google_drive' gem
# $ gem install google_drive
# Or add `gem 'google_drive'` to your Gemfile
#
# It is initialized with a file_path for the file to upload, the drive_folder_id
# for the destination folder in Google Drive, and optional file_name to use in Drive.
#
# Example usage: Automatically upload reports generated by AI to a shared Google Drive folder.

require 'google_drive'

class GoogleDriveUploadFileAction < Sublayer::Actions::Base
  def initialize(file_path:, drive_folder_id:, file_name: nil)
    @file_path = file_path
    @drive_folder_id = drive_folder_id
    @file_name = file_name || File.basename(file_path)
    @session = GoogleDrive::Session.from_config("config.json")
  end

  def call
    begin
      upload_file_to_drive
      Sublayer.configuration.logger.log(:info, "Successfully uploaded #{@file_name} to Google Drive folder #{@drive_folder_id}")
    rescue Google::Apis::Error => e
      error_message = "Error uploading file to Google Drive: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    rescue StandardError => e
      error_message = "Unexpected error: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise e
    end
  end

  private

  def upload_file_to_drive
    folder = @session.collection_by_id(@drive_folder_id)
    folder.upload_from_file(@file_path, @file_name, convert: false)
  end
end
