require 'google/apis/drive_v3'
require 'googleauth'

# Description: Sublayer::Action responsible for uploading a file to a specified Google Drive folder.
# This action facilitates the storage and organization of LLM-generated outputs or any other files
# directly from the Sublayer workflow.
#
# It is initialized with a file_path and folder_id, and uploads the file to the specified Google Drive folder.
#
# Requires: 'google-api-client' gem
# $ gem install google-api-client
# Or add `gem 'google-api-client'` to your Gemfile
#
# Example usage: When you want to save files generated by an LLM to Google Drive for sharing or backup.

class GoogleDriveFileUploadAction < Sublayer::Actions::Base
  GOOGLE_DRIVE_SCOPE = 'https://www.googleapis.com/auth/drive.file'

  def initialize(file_path:, folder_id:)
    @file_path = file_path
    @folder_id = folder_id
    @drive_service = initialize_drive_service
  end

  def call
    begin
      file_metadata = {
        name: File.basename(@file_path),
        parents: [@folder_id]
      }
      upload_file = File.open(@file_path)
      result = @drive_service.create_file(file_metadata, upload_source: upload_file, content_type: 'application/octet-stream')
      Sublayer.configuration.logger.log(:info, "File uploaded successfully to Google Drive with ID: #{result.id}")
      result.id
    rescue Google::Apis::ClientError => e
      error_message = "Error uploading file to Google Drive: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    rescue StandardError => e
      error_message = "Unexpected error: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise e
    ensure
      upload_file.close if upload_file
    end
  end

  private

  def initialize_drive_service
    drive_service = Google::Apis::DriveV3::DriveService.new
    drive_service.client_options.application_name = 'Sublayer'
    drive_service.authorization = Google::Auth.get_application_default([GOOGLE_DRIVE_SCOPE])
    drive_service
  end
end
