require 'twilio-ruby'

# Description: Sublayer::Action responsible for sending an SMS message using Twilio's API.
# This action is useful for real-time notifications or alerts generated by AI workflows.
#
# It is initialized with a to phone number, from phone number, and message body.
# It returns the SID of the sent message to confirm it was sent successfully.
#
# Example usage: When you want to send an alert or notification from an AI process via SMS.

class TwilioSendSmsAction < Sublayer::Actions::Base
  def initialize(to:, from:, body:)
    @to = to
    @from = from
    @body = body
    @client = Twilio::REST::Client.new(ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN'])
  end

  def call
    begin
      message = @client.messages.create(
        from: @from,
        to: @to,
        body: @body
      )
      Sublayer.configuration.logger.log(:info, "SMS sent successfully to #{@to}. Message SID: #{message.sid}")
      message.sid
    rescue Twilio::REST::TwilioError => e
      error_message = "Error sending SMS via Twilio: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end
end
