# Description: Sublayer::Action responsible for sending SMS notifications using the Twilio API.
# This action is useful for sending urgent alerts or updates generated by AI processes that require immediate attention.
#
# It is initialized with a phone number and a message.
# It returns the Twilio message SID to confirm the SMS was sent successfully.
#
# Example usage: When you want to send a high-priority alert or notification to someone's phone.

require 'twilio-ruby'

class TwilioSmsNotificationAction < Sublayer::Actions::Base
  def initialize(to_phone_number:, message:)
    @to_phone_number = to_phone_number
    @message = message
    @client = Twilio::REST::Client.new(ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN'])
  end

  def call
    send_sms
  rescue Twilio::REST::TwilioError => e
    error_message = "Twilio error: #{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise StandardError, error_message
  rescue StandardError => e
    error_message = "Error sending SMS via Twilio: #{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise e
  end

  private

  def send_sms
    message = @client.messages.create(
      from: ENV['TWILIO_PHONE_NUMBER'],
      to: @to_phone_number,
      body: @message
    )

    Sublayer.configuration.logger.log(:info, "SMS sent successfully via Twilio with SID: #{message.sid}")
    message.sid
  end
end
