require 'twilio-ruby'

# Description: Sublayer::Action responsible for sending SMS notifications using Twilio.
# This action is useful for alerting users of important updates or events generated by the AI workflow.
#
# It is initialized with a recipient phone number, a message, and an optional sender phone number (Twilio number).
# It returns the SID of the sent message to confirm it was sent successfully.
#
# Example usage: When you want to send a notification or update from an AI process to a user's phone as an SMS.

class TwilioSmsNotificationAction < Sublayer::Actions::Base
  def initialize(to:, message:, from: ENV['TWILIO_PHONE_NUMBER'])
    @to = to
    @message = message
    @from = from
    @client = Twilio::REST::Client.new(ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN'])
  end

  def call
    begin
      message = @client.messages.create(
        from: @from,
        to: @to,
        body: @message
      )
      Sublayer.configuration.logger.log(:info, "SMS sent successfully to #{@to}")
      message.sid
    rescue Twilio::REST::TwilioError => e
      error_message = "Error sending SMS via Twilio: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end
end