require 'restforce'

# Description: Sublayer::Action responsible for updating an existing opportunity in Salesforce.
# This action allows for easy integration of Salesforce CRM updates into Sublayer workflows.
#
# It is initialized with an opportunity_id and a hash of updated fields.
# It returns the updated opportunity's ID on success.
#
# Example usage: When you want to update Salesforce opportunities with new data generated by AI insights.

class SalesforceOpportunityUpdateAction < Sublayer::Actions::Base
  def initialize(opportunity_id:, updated_fields:, **kwargs)
    super(**kwargs)
    @opportunity_id = opportunity_id
    @updated_fields = updated_fields
    @client = Restforce.new(
      username: ENV['SALESFORCE_USERNAME'],
      password: ENV['SALESFORCE_PASSWORD'],
      security_token: ENV['SALESFORCE_SECURITY_TOKEN'],
      client_id: ENV['SALESFORCE_CLIENT_ID'],
      client_secret: ENV['SALESFORCE_CLIENT_SECRET'],
      host: ENV['SALESFORCE_HOST']
    )
  end

  def call
    update_opportunity
  rescue Restforce::Error => e
    error_message = "Error updating Salesforce opportunity: #{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise StandardError, error_message
  rescue StandardError => e
    error_message = "Unexpected error: #{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise e
  end

  private

  def update_opportunity
    response = @client.update('Opportunity', Id: @opportunity_id, **@updated_fields)
    if response
      Sublayer.configuration.logger.log(:info, "Opportunity updated successfully in Salesforce with ID: #{@opportunity_id}")
      @opportunity_id
    else
      error_message = "Failed to update opportunity with ID: #{@opportunity_id}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end
end
