require 'restforce'

# Description: Sublayer::Action responsible for creating a new contact in Salesforce.
# This action is designed to capture leads generated or analyzed by an LLM into Salesforce.
#
# It is initialized with details required for creating a Salesforce contact such as first_name, last_name, email, etc.
# It returns the ID of the created contact.
#
# Example usage: When you have a lead generated by an AI model and you want to save it in Salesforce.

class SalesforceContactCreateAction < Sublayer::Actions::Base
  def initialize(first_name:, last_name:, email:, phone: nil, **additional_fields)
    @first_name = first_name
    @last_name = last_name
    @phone = phone
    @additional_fields = additional_fields
    @client = Restforce.new(
      username: ENV['SALESFORCE_USERNAME'],
      password: ENV['SALESFORCE_PASSWORD'],
      security_token: ENV['SALESFORCE_SECURITY_TOKEN'],
      client_id: ENV['SALESFORCE_CLIENT_ID'],
      client_secret: ENV['SALESFORCE_CLIENT_SECRET']
    )
  end

  def call
    create_contact
  rescue Restforce::Error => e
    error_message = "Error creating Salesforce contact: #{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise StandardError, error_message
  end

  private

  def create_contact
    contact_params = {
      FirstName: @first_name,
      LastName: @last_name,
      Email: @email
    }
    contact_params[:Phone] = @phone if @phone
    contact_params.merge!(@additional_fields)

    contact = @client.create('Contact', contact_params)
    Sublayer.configuration.logger.log(:info, "Contact created successfully in Salesforce with ID: #{contact}")
    contact
  end
end