require 'restforce'

# Description: Sublayer::Action responsible for inserting lead information into Salesforce.
# This action integrates with Salesforce using the Restforce gem, supporting CRM integration and management.
#
# It is initialized with lead information such as name, company, and email.
# It returns the ID of the created lead.
#
# Example usage: When you have a new lead generated by an AI process or extracted from a data source and need to insert it into Salesforce for further CRM activities.

class SalesforceLeadInsertionAction < Sublayer::Actions::Base
  def initialize(first_name:, last_name:, company:, email:, **kwargs)
    @first_name = first_name
    @last_name = last_name
    @company = company
    @email = email
    @client = Restforce.new(
      username: ENV['SALESFORCE_USERNAME'],
      password: ENV['SALESFORCE_PASSWORD'],
      security_token: ENV['SALESFORCE_SECURITY_TOKEN'],
      client_id: ENV['SALESFORCE_CLIENT_ID'],
      client_secret: ENV['SALESFORCE_CLIENT_SECRET'],
      host: ENV['SALESFORCE_HOST']
    )
  end

  def call
    begin
      lead = create_lead
      Sublayer.configuration.logger.log(:info, "Lead created successfully in Salesforce with ID: #{lead.Id}")
      lead.Id
    rescue Restforce::Error => e
      error_message = "Error creating Salesforce lead: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    rescue StandardError => e
      error_message = "General error: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise e
    end
  end

  private

  def create_lead
    @client.create('Lead', {
      FirstName: @first_name,
      LastName: @last_name,
      Company: @company,
      Email: @email
    })
  end
end
