# Description: Sublayer::Action responsible for scheduling a Zoom meeting and sending invites.
# This action integrates with the Zoom API to automatically create and send invitations for meetings
# based on input details such as participants, time, and agenda generated by AI suggestions.
#
# It is initialized with the meeting topic, agenda, start_time, duration, and an array of participant emails.
# It returns the meeting ID and join URL upon successful scheduling.
#
# Example usage: When you want to schedule a meeting with multiple participants based on AI-suggested times and topics.

require 'net/http'
require 'uri'
require 'json'
require 'base64'

class ZoomScheduleMeetingAction < Sublayer::Actions::Base
  def initialize(topic:, agenda:, start_time:, duration:, participants: [])
    @topic = topic
    @agenda = agenda
    @start_time = start_time
    @duration = duration
    @participants = participants
    @zoom_api_key = ENV['ZOOM_API_KEY']
    @zoom_api_secret = ENV['ZOOM_API_SECRET']
  end

  def call
    schedule_meeting
  rescue StandardError => e
    error_message = "Error scheduling Zoom meeting: #{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise e
  end

  private

  def schedule_meeting
    uri = URI.parse('https://api.zoom.us/v2/users/me/meetings')
    header = {
      'Content-Type' => 'application/json',
      'Authorization' => "Bearer #{generate_jwt_token}"
    }

    body = {
      topic: @topic,
      agenda: @agenda,
      start_time: @start_time,
      duration: @duration,
      settings: {
        participant_video: true,
        join_before_host: false
      }
    }

    request = Net::HTTP::Post.new(uri, header)
    request.body = body.to_json

    response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
      http.request(request)
    end

    if response.is_a?(Net::HTTPSuccess)
      meeting_info = JSON.parse(response.body)
      send_invites(meeting_info['join_url'], meeting_info['id'])
      Sublayer.configuration.logger.log(:info, "Zoom meeting scheduled successfully with ID: #{meeting_info['id']}")
      meeting_info.slice('id', 'join_url')
    else
      error_message = "Failed to schedule Zoom meeting: HTTP #{response.code} - #{response.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end

  def send_invites(join_url, meeting_id)
    # Here, implement the logic to send out email invites to each participant.
    # This can be done via an SMTP library or a service like SendGrid or AWS SES.
    @participants.each do |email|
      Sublayer.configuration.logger.log(:info, "Sending Zoom invite to #{email} for meeting ID: #{meeting_id}")
      # Placeholder for sending email logic.
    end
  end

  def generate_jwt_token
    payload = {
      iss: @zoom_api_key,
      exp: (Time.now + 3600).to_i
    }
    JWT.encode(payload, @zoom_api_secret, 'HS256')
  end
end
