require 'google/cloud/translate'

# Description: Sublayer::Action responsible for translating text between specified languages using Google Cloud Translation API.
# This action facilitates multilingual support within Sublayer workflows, enabling translation of text-based data.
#
# Requires: `google-cloud-translate` gem
# $ gem install google-cloud-translate
# Or add `gem 'google-cloud-translate'` to your Gemfile
#
# It is initialized with text to translate, source language, and target language.
# Returns the translated text.
#
# Example usage: Translate text inputs from users or text generated by an AI to a preferred language for further processing or user interaction.

class TranslateTextAction < Sublayer::Actions::Base
  def initialize(text:, source_language:, target_language:)
    @text = text
    @source_language = source_language
    @target_language = target_language
    @translate = Google::Cloud::Translate.new(version: :v2, key: ENV['GOOGLE_TRANSLATE_API_KEY'])
  end

  def call
    begin
      translation = @translate.translate(@text, from: @source_language, to: @target_language)
      Sublayer.configuration.logger.log(:info, "Successfully translated text from #{@source_language} to #{@target_language}")
      translation.text
    rescue Google::Cloud::Error => e
      error_message = "Error during translation: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end
end