require 'aws-sdk-s3'

# Description: Sublayer::Action responsible for uploading files to an AWS S3 bucket.
# This action ensures data generated by Sublayer Generators is persisted in the cloud for easy access and sharing.
#
# It is initialized with bucket_name, file_path, and optionally object_key and acl.
# It returns the public URL of the uploaded object if successful.
#
# Example usage: Automatically upload important data outputs from AI processing to S3 for backup or sharing.

class AwsS3FileUploadAction < Sublayer::Actions::Base
  def initialize(bucket_name:, file_path:, object_key: nil, acl: 'private')
    @bucket_name = bucket_name
    @file_path = file_path
    @object_key = object_key || File.basename(file_path)
    @acl = acl
    @s3_client = Aws::S3::Client.new(region: ENV['AWS_REGION'], access_key_id: ENV['AWS_ACCESS_KEY_ID'], secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'])
  end

  def call
    upload_file
  rescue Aws::S3::Errors::ServiceError => e
    error_message = "Error uploading file to S3: #{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise StandardError, error_message
  rescue StandardError => e
    error_message = "Unexpected error: #{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise e
  end

  private

  def upload_file
    @s3_client.put_object(
      bucket: @bucket_name,
      key: @object_key,
      body: File.read(@file_path),
      acl: @acl
    )
    public_url = "https://#{@bucket_name}.s3.amazonaws.com/#{@object_key}"
    Sublayer.configuration.logger.log(:info, "File uploaded successfully to S3: #{public_url}")
    public_url
  end
end