require 'aws-sdk-s3'

# Description: Sublayer::Action responsible for uploading files to an AWS S3 bucket.
# This action allows for easy integration with AWS S3, enabling easy storage and retrieval of files.
#
# It is initialized with a bucket_name, file_path, and an optional s3_key.
# It returns the public URL of the uploaded file.
#
# Example usage: When you want to upload a file generated by an AI process to AWS S3 for persistent storage.

class AwsS3UploadAction < Sublayer::Actions::Base
  def initialize(bucket_name:, file_path:, s3_key: nil)
    @bucket_name = bucket_name
    @file_path = file_path
    @s3_key = s3_key || File.basename(file_path)
    @s3_client = Aws::S3::Client.new(region: ENV['AWS_REGION'], access_key_id: ENV['AWS_ACCESS_KEY_ID'], secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'])
  end

  def call
    begin
      upload_file_to_s3
      file_url
    rescue Aws::S3::Errors::ServiceError => e
      error_message = "AWS S3 upload failed: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    rescue StandardError => e
      error_message = "Error during S3 upload: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise e
    end
  end

  private

  def upload_file_to_s3
    @s3_client.put_object(bucket: @bucket_name, key: @s3_key, body: File.read(@file_path))
    Sublayer.configuration.logger.log(:info, "File uploaded successfully to bucket #{@bucket_name} with key #{@s3_key}")
  end

  def file_url
    @s3_client.get_object_acl(bucket: @bucket_name, key: @s3_key)
    "https://#{@bucket_name}.s3.amazonaws.com/#{@s3_key}"
  end
end