require 'aws-sdk-s3'

# Description: Sublayer::Action responsible for uploading files to an AWS S3 bucket.
# This action allows secure storage of generated files or logs in the cloud.
#
# It is initialized with the S3 bucket name, the file path to upload, and the key (path in the bucket).
# Returns the public URL of the uploaded file.
#
# Example usage: When you need to store logs or files generated by an AI process to an S3 bucket.

class AWSS3FileUploaderAction < Sublayer::Actions::Base
  def initialize(bucket_name:, file_path:, key:)
    @bucket_name = bucket_name
    @file_path = file_path
    @key = key
    @s3_client = Aws::S3::Client.new(region: ENV['AWS_REGION'], access_key_id: ENV['AWS_ACCESS_KEY_ID'], secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'])
  end

  def call
    begin
      upload_file
      public_url
    rescue Aws::S3::Errors::ServiceError => e
      Sublayer.configuration.logger.log(:error, "Error uploading file to S3: #{e.message}")
      raise StandardError, "Failed to upload file to S3"
    end
  end

  private

  def upload_file
    @s3_client.put_object(
      bucket: @bucket_name,
      key: @key,
      body: File.open(@file_path, 'rb')
    )
    Sublayer.configuration.logger.log(:info, "File uploaded successfully to S3 bucket #{@bucket_name} as #{@key}")
  end

  def public_url
    "https://#{@bucket_name}.s3.amazonaws.com/#{@key}"
  end
end