require 'aws-sdk-s3'

# Description: Sublayer::Action responsible for uploading files to an AWS S3 bucket.
# This action allows integrating AWS S3 storage into Sublayer workflows,
# making it easy to store and retrieve data from the cloud.
#
# It is initialized with bucket_name, file_path, and optionally key and content_type.
# It uploads the specified file to the given S3 bucket and returns the object URL.
#
# Example usage: When you need to upload files generated by AI processes to
# AWS S3 for persistent storage or sharing with other systems.

class AwsS3UploadAction < Sublayer::Actions::Base
  def initialize(bucket_name:, file_path:, key: nil, content_type: nil)
    @bucket_name = bucket_name
    @file_path = file_path
    @key = key || File.basename(file_path)
    @content_type = content_type || 'application/octet-stream'
    @client = Aws::S3::Client.new(region: ENV['AWS_REGION'],
                                   access_key_id: ENV['AWS_ACCESS_KEY_ID'],
                                   secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'])
  end

  def call
    upload_file
  rescue Aws::S3::Errors::ServiceError => e
    error_message = "Error uploading to S3: #{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise StandardError, error_message
  end

  private

  def upload_file
    @client.put_object(bucket: @bucket_name, 
                       key: @key,
                       body: File.open(@file_path, 'rb'),
                       content_type: @content_type)
    object_url = "https://#{@bucket_name}.s3.amazonaws.com/#{@key}"
    Sublayer.configuration.logger.log(:info, "File uploaded successfully to S3: #{object_url}")
    object_url
  end
end