require 'aws-sdk-s3'

# Description: Sublayer::Action responsible for uploading files to an AWS S3 bucket.
# This action helps in storing results or backups of data generated by AI processes.
#
# It is initialized with a bucket_name, file_path, and optionally, an object_key.
# By default, the object_key is set to the file name. It returns the public URL of the uploaded object.
#
# Example usage: When you want to upload a generated report or backup data to S3 for persistence.

class AwsS3FileUploadAction < Sublayer::Actions::Base
  def initialize(bucket_name:, file_path:, object_key: nil)
    @bucket_name = bucket_name
    @file_path = file_path
    @object_key = object_key || File.basename(file_path)
    @client = Aws::S3::Client.new(region: ENV['AWS_REGION'],
                                 access_key_id: ENV['AWS_ACCESS_KEY_ID'],
                                 secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'])
  end

  def call
    begin
      upload_file
      public_url
    rescue Aws::S3::Errors::ServiceError => e
      error_message = "Error uploading file to S3: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end

  private

  def upload_file
    @client.put_object(bucket: @bucket_name, key: @object_key, body: File.read(@file_path))
    Sublayer.configuration.logger.log(:info, "Successfully uploaded #{File.basename(@file_path)} to #{@bucket_name}/#{@object_key}")
  end

  def public_url
    "https://#{@bucket_name}.s3.amazonaws.com/#{@object_key}"
  end
end
