require 'aws-sdk-s3'

# Description: Sublayer::Action responsible for uploading a file to an AWS S3 bucket.
# This action facilitates data storage or backup by integrating with AWS S3.
#
# It is initialized with a file_path, bucket_name, and optionally a key (path in the bucket).
# It returns the public URL of the uploaded file.
#
# Example usage: To store backup files or upload data generated by AI processes to an S3 bucket.

class AwsS3UploadFileAction < Sublayer::Actions::Base
  def initialize(file_path:, bucket_name:, key: nil)
    @file_path = file_path
    @bucket_name = bucket_name
    @key = key || File.basename(file_path)
    @s3_client = Aws::S3::Client.new(region: ENV['AWS_REGION'], access_key_id: ENV['AWS_ACCESS_KEY_ID'], secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'])
  end

  def call
    begin
      upload_file
      public_url = generate_public_url
      Sublayer.configuration.logger.log(:info, "File uploaded successfully to S3 at #{public_url}")
      public_url
    rescue Aws::S3::Errors::ServiceError => e
      error_message = "Error uploading file to S3: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    rescue StandardError => e
      error_message = "Unexpected error during S3 upload: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise e
    end
  end

  private

  def upload_file
    File.open(@file_path, 'rb') do |file|
      @s3_client.put_object(bucket: @bucket_name, key: @key, body: file)
    end
  end

  def generate_public_url
    "https://#{@bucket_name}.s3.amazonaws.com/#{@key}"
  end
end
