require 'aws-sdk-s3'

# Description: Sublayer::Action responsible for uploading files to an AWS S3 bucket.
# This action facilitates integration with AWS S3, making it simple to upload files directly from
# Sublayer workflows, useful for storing logs, reports, or any AI-generated outputs needing archiving or sharing.
#
# It is initialized with a bucket_name, file_path, and optional key for S3 object.
# It returns the public URL of the uploaded file upon success.
#
# Example usage: When you want to store outputs like reports or logs generated by AI processes to S3 for easy access and archiving.

class AwsS3FileUploadAction < Sublayer::Actions::Base
  def initialize(bucket_name:, file_path:, object_key: nil)
    @bucket_name = bucket_name
    @file_path = file_path
    @object_key = object_key || File.basename(file_path)
    @s3_client = Aws::S3::Client.new(region: ENV['AWS_REGION'],
                                     access_key_id: ENV['AWS_ACCESS_KEY_ID'],
                                     secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'])
  end

  def call
    begin
      upload_file
      public_url
    rescue Aws::S3::Errors::ServiceError => e
      error_message = "Error uploading file: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end

  private

  def upload_file
    @s3_client.put_object(
      bucket: @bucket_name,
      key: @object_key,
      body: File.read(@file_path)
    )
    Sublayer.configuration.logger.log(:info, "File successfully uploaded to S3: #{@bucket_name}/#{@object_key}")
  end

  def public_url
    "https://#{@bucket_name}.s3.amazonaws.com/#{@object_key}"
  end
end
