require 'aws-sdk-s3'

# Description: Sublayer::Action responsible for uploading files to an Amazon S3 bucket.
# This action enables storage and backup solutions for files generated by AI tasks or other actions.
#
# It is initialized with a bucket_name, file_path, and optionally, s3_key (the key under which the file will be stored in the bucket).
# It returns the public URL of the uploaded file.
#
# Example usage: When you need to store generated reports or data to make them accessible from anywhere, use this action to upload them to S3.

class AwsS3FileUploadAction < Sublayer::Actions::Base
  def initialize(bucket_name:, file_path:, s3_key: nil)
    @bucket_name = bucket_name
    @file_path = file_path
    @s3_key = s3_key || File.basename(file_path)
    @client = Aws::S3::Client.new(region: 'us-east-1')
  end

  def call
    upload_file
    public_url
  rescue Aws::S3::Errors::ServiceError => e
    error_message = "Error uploading file to S3: #{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise StandardError, error_message
  end

  private

  def upload_file
    @client.put_object(
      bucket: @bucket_name,
      key: @s3_key,
      body: File.read(@file_path)
    )
    Sublayer.configuration.logger.log(:info, "File uploaded successfully to #{@bucket_name}/#{@s3_key}")
  end

  def public_url
    "https://#{@bucket_name}.s3.amazonaws.com/#{@s3_key}"
  end
end
