require 'aws-sdk-s3'

# Description: Sublayer::Action responsible for uploading files to Amazon S3.
# This action provides a simple interface to upload files to S3 with configurable
# permissions and metadata, useful for storing AI-generated assets, backups,
# or intermediate files in workflows.
#
# Requires: 'aws-sdk-s3' gem
# $ gem install aws-sdk-s3
# Or add `gem 'aws-sdk-s3'` to your Gemfile
#
# It is initialized with the bucket name, file path, and optional parameters for
# S3 configuration like ACL, metadata, and storage class.
#
# Example usage: When you want to store files generated by AI processes or
# save intermediate workflow results to S3 for later use.

class S3FileUploadAction < Sublayer::Actions::Base
  def initialize(
    bucket:,
    file_path:,
    s3_key: nil,
    acl: 'private',
    metadata: {},
    storage_class: 'STANDARD',
    region: ENV['AWS_REGION'] || 'us-east-1'
  )
    @bucket = bucket
    @file_path = file_path
    @s3_key = s3_key || File.basename(@file_path)
    @acl = acl
    @metadata = metadata
    @storage_class = storage_class
    @region = region

    @client = Aws::S3::Client.new(
      region: @region,
      credentials: Aws::Credentials.new(
        ENV['AWS_ACCESS_KEY_ID'],
        ENV['AWS_SECRET_ACCESS_KEY']
      )
    )
  end

  def call
    begin
      validate_file
      upload_file
      Sublayer.configuration.logger.log(:info, "Successfully uploaded #{@file_path} to S3 bucket #{@bucket} with key #{@s3_key}")
      
      # Return the S3 URL of the uploaded file
      "https://#{@bucket}.s3.#{@region}.amazonaws.com/#{@s3_key}"
    rescue Aws::S3::Errors::ServiceError => e
      error_message = "AWS S3 error: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    rescue StandardError => e
      error_message = "Error uploading file to S3: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise e
    end
  end

  private

  def validate_file
    unless File.exist?(@file_path)
      raise StandardError, "File not found: #{@file_path}"
    end

    unless File.readable?(@file_path)
      raise StandardError, "File is not readable: #{@file_path}"
    end
  end

  def upload_file
    File.open(@file_path, 'rb') do |file|
      @client.put_object(
        bucket: @bucket,
        key: @s3_key,
        body: file,
        acl: @acl,
        metadata: @metadata,
        storage_class: @storage_class
      )
    end
  end
end