require 'aws-sdk-s3'

# Description: Sublayer::Action responsible for uploading a file to AWS S3.
# This action enables storing files generated by AI workflows (such as images or documents)
# in a persistent S3 storage with configurable permissions and metadata.
#
# Requires: 'aws-sdk-s3' gem
# $ gem install aws-sdk-s3
# Or add `gem 'aws-sdk-s3'` to your Gemfile
#
# It is initialized with a bucket name, file path, and optional parameters for S3 configuration.
# It returns the URL of the uploaded file in S3.
#
# Example usage: When you want to store AI-generated files (like DALL-E images) in S3
# for persistent storage and sharing.

class S3UploadFileAction < Sublayer::Actions::Base
  def initialize(bucket:, file_path:, s3_key: nil, acl: 'private', metadata: {}, content_type: nil)
    @bucket = bucket
    @file_path = file_path
    @s3_key = s3_key || File.basename(@file_path)
    @acl = acl
    @metadata = metadata
    @content_type = content_type || detect_content_type
    
    @client = Aws::S3::Client.new(
      region: ENV['AWS_REGION'] || 'us-east-1',
      credentials: Aws::Credentials.new(
        ENV['AWS_ACCESS_KEY_ID'],
        ENV['AWS_SECRET_ACCESS_KEY']
      )
    )
  end

  def call
    begin
      validate_file
      upload_file
      generate_url
    rescue Aws::S3::Errors::ServiceError => e
      error_message = "AWS S3 error: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    rescue StandardError => e
      error_message = "Error uploading file to S3: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise e
    end
  end

  private

  def validate_file
    unless File.exist?(@file_path)
      raise StandardError, "File not found: #{@file_path}"
    end
  end

  def detect_content_type
    case File.extname(@file_path).downcase
    when '.jpg', '.jpeg'
      'image/jpeg'
    when '.png'
      'image/png'
    when '.gif'
      'image/gif'
    when '.pdf'
      'application/pdf'
    when '.txt'
      'text/plain'
    when '.json'
      'application/json'
    else
      'application/octet-stream'
    end
  end

  def upload_file
    File.open(@file_path, 'rb') do |file|
      params = {
        bucket: @bucket,
        key: @s3_key,
        body: file,
        acl: @acl,
        content_type: @content_type,
        metadata: @metadata
      }

      @client.put_object(params)
    end

    Sublayer.configuration.logger.log(:info, "Successfully uploaded #{@file_path} to S3 bucket #{@bucket}")
  end

  def generate_url
    if @acl == 'public-read'
      "https://#{@bucket}.s3.amazonaws.com/#{@s3_key}"
    else
      presigned_url = @client.generate_presigned_url(
        'get_object',
        bucket: @bucket,
        key: @s3_key,
        expires_in: 3600 # URL expires in 1 hour
      )
      
      Sublayer.configuration.logger.log(:info, "Generated presigned URL for #{@s3_key}")
      presigned_url
    end
  end
end