require 'aws-sdk-s3'

# Description: Sublayer::Action responsible for uploading a file to an AWS S3 bucket.
# This action enables storing files generated by AI workflows in S3 cloud storage.
#
# Requires: 'aws-sdk-s3' gem
# $ gem install aws-sdk-s3
# Or add `gem 'aws-sdk-s3'` to your Gemfile
#
# It is initialized with the bucket name, file path (local), destination key (S3 path),
# and optional metadata and content type.
# It returns the S3 object URL of the uploaded file.
#
# Example usage: When you want to store AI-generated files (images, documents, data)
# in AWS S3 for later access or distribution.

class S3UploadFileAction < Sublayer::Actions::Base
  def initialize(bucket:, file_path:, destination_key:, metadata: {}, content_type: nil)
    @bucket = bucket
    @file_path = file_path
    @destination_key = destination_key
    @metadata = metadata
    @content_type = content_type
    @client = Aws::S3::Client.new(
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      region: ENV['AWS_REGION']
    )
  end

  def call
    begin
      validate_file!
      upload_file
    rescue Aws::S3::Errors::ServiceError => e
      error_message = "AWS S3 error during upload: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    rescue StandardError => e
      error_message = "Error uploading file to S3: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise e
    end
  end

  private

  def validate_file!
    unless File.exist?(@file_path)
      error_message = "File not found at path: #{@file_path}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end

  def upload_file
    options = {
      bucket: @bucket,
      key: @destination_key,
      body: File.open(@file_path, 'rb'),
      metadata: @metadata
    }

    options[:content_type] = @content_type if @content_type

    response = @client.put_object(options)

    object_url = "https://#{@bucket}.s3.#{ENV['AWS_REGION']}.amazonaws.com/#{@destination_key}"
    
    Sublayer.configuration.logger.log(:info, "Successfully uploaded file to S3: #{object_url}")
    
    object_url
  end
end