require 'google/apis/calendar_v3'
require 'googleauth'
require 'googleauth/stores/file_token_store'

require 'fileutils'

OOB_URI = 'urn:ietf:wg:oauth:2.0:oob'.freeze
CREDENTIALS_PATH = 'token.yaml'.freeze

# Description: Sublayer::Action responsible for creating an event in a Google Calendar.
#
# It is initialized with a calendar_id, start_time, end_time, summary, and description.
# It returns the event id of the created event.
#
# Example usage: When you want to automatically create calendar events based on
# meeting summaries or scheduled tasks generated by an LLM.

class GoogleCalendarCreateEventAction < Sublayer::Actions::Base
  def initialize(calendar_id:, start_time:, end_time:, summary:, description:)
    @calendar_id = calendar_id
    @start_time = start_time
    @end_time = end_time
    @summary = summary
    @description = description
  end

  def call
    event = create_event
    event.id
  rescue StandardError => e
    error_message = "Error creating Google Calendar event: #{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise StandardError, error_message
  end

  private

  ##
  # Ensure valid credentials, either by fetching from the save file
  # or intitiating an OAuth2 authorization. If authorization is required,
  # the user's default browser will be launched to approve the request.
  #
  # @return [Google::Auth::UserRefreshCredentials]
  def authorize
    client_id = Google::Auth::ClientId.from_file(ENV['GOOGLE_CLIENT_SECRET_PATH'])
    token_store = Google::Auth::Stores::FileTokenStore.new(file: CREDENTIALS_PATH)
    authorizer = Google::Auth::UserAuthorizer.new(client_id, Google::Apis::CalendarV3::AUTH_CALENDAR, token_store)
    user_id = 'default'
    credentials = authorizer.get_credentials(user_id)
    if credentials.nil?
      url = authorizer.get_authorization_url(base_url: OOB_URI)
      puts "Open the following URL in the browser and enter the " \
           "resulting code after authorization:\n" + url
      code = gets
      credentials = authorizer.get_and_store_credentials_from_code(
        user_id: user_id, code: code, base_url: OOB_URI
      )
    end
    credentials
  end

  def create_event
    # Initialize the API
    calendar = Google::Apis::CalendarV3::CalendarService.new
    calendar.client_options.application_name = 'Sublayer Action'
    calendar.authorization = authorize

    event = Google::Apis::CalendarV3::Event.new(
      summary: @summary,
      description: @description,
      start: Google::Apis::CalendarV3::EventDateTime.new(date_time: @start_time.rfc3339),
      end: Google::Apis::CalendarV3::EventDateTime.new(date_time: @end_time.rfc3339)
    )

    calendar.insert_event(@calendar_id, event)
  end
end