require 'google/apis/calendar_v3'
require 'googleauth'
require 'googleauth/stores/file_token_store'

# Description: Sublayer::Action responsible for creating a new event in Google Calendar.
# This action can be used to automate scheduling meetings or reminders generated by AI processes.
#
# It is initialized with calendar_id, summary, start_time, end_time, and optional description and location.
# It returns the ID of the created event.
#
# Example usage: Scheduling AI-suggested meetings seamlessly into a user's Google Calendar.

class GoogleCalendarCreateEventAction < Sublayer::Actions::Base
  OOB_URI = 'urn:ietf:wg:oauth:2.0:oob'.freeze
  APPLICATION_NAME = 'Sublayer Google Calendar API'.freeze
  CREDENTIALS_PATH = 'path/to/credentials.json'.freeze
  TOKEN_PATH = 'token.yaml'.freeze
  SCOPE = Google::Apis::CalendarV3::AUTH_CALENDAR

  def initialize(calendar_id:, summary:, start_time:, end_time:, description: nil, location: nil)
    @calendar_id = calendar_id
    @summary = summary
    @start_time = start_time
    @end_time = end_time
    @description = description
    @location = location
    @service = initialize_google_calendar_service
  end

  def call
    begin
      event = create_event
      created_event = @service.insert_event(@calendar_id, event)
      Sublayer.configuration.logger.log(:info, "Google Calendar event created with ID: #{created_event.id}")
      created_event.id
    rescue Google::Apis::Error => e
      error_message = "Error creating Google Calendar event: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end

  private

  def initialize_google_calendar_service
    client_id = Google::Auth::ClientId.from_file(CREDENTIALS_PATH)
    token_store = Google::Auth::Stores::FileTokenStore.new(file: TOKEN_PATH)
    authorizer = Google::Auth::UserAuthorizer.new(client_id, SCOPE, token_store)
    user_id = 'user@example.com'
    credentials = authorizer.get_credentials(user_id)
    if credentials.nil?
      url = authorizer.get_authorization_url(base_url: OOB_URI)
      puts "Open the following URL in the browser and enter the resulting code after authorization: #{url}"
      code = gets
      credentials = authorizer.get_and_store_credentials_from_code(user_id: user_id, code: code, base_url: OOB_URI)
    end
    service = Google::Apis::CalendarV3::CalendarService.new
    service.client_options.application_name = APPLICATION_NAME
    service.authorization = credentials
    service
  end

  def create_event
    Google::Apis::CalendarV3::Event.new(
      summary: @summary,
      location: @location,
      description: @description,
      start: Google::Apis::CalendarV3::EventDateTime.new(
        date_time: @start_time.to_datetime.rfc3339
      ),
      end: Google::Apis::CalendarV3::EventDateTime.new(
        date_time: @end_time.to_datetime.rfc3339
      )
    )
  end
end
