require 'google/apis/calendar_v3'
require 'googleauth'
require 'googleauth/stores/file_token_store'
require 'tmpdir'
require 'fileutils'

# Description: Sublayer::Action responsible for creating an event in a specified Google Calendar.
# This action allows for creating calendar events with a title, description, start and end times, and attendees.
#
# Example usage: When you need to schedule a new meeting or event using the information generated by an AI model.

class GoogleCalendarEventCreateAction < Sublayer::Actions::Base
  OOB_URI = 'urn:ietf:wg:oauth:2.0:oob'
  APPLICATION_NAME = 'Google Calendar API Ruby Quickstart'
  CREDENTIALS_PATH = 'credentials.json'
  TOKEN_PATH = File.join(Dir.tmpdir, "token.yaml")
  SCOPE = Google::Apis::CalendarV3::AUTH_CALENDAR

  def initialize(calendar_id:, event_title:, event_description:, start_time:, end_time:, attendees: [])
    @calendar_id = calendar_id
    @event_title = event_title
    @event_description = event_description
    @start_time = start_time
    @end_time = end_time
    @attendees = attendees.map { |email| { email: email } }
    @service = Google::Apis::CalendarV3::CalendarService.new
    @service.client_options.application_name = APPLICATION_NAME
    @service.authorization = authorize
  end

  def call
    begin
      create_event
      Sublayer.configuration.logger.log(:info, "Event created successfully in Google Calendar")
    rescue Google::Apis::Error => e
      error_message = "Error creating Google Calendar event: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end

  private

  def authorize
    client_id = Google::Auth::ClientId.from_file(CREDENTIALS_PATH)
    token_store = Google::Auth::Stores::FileTokenStore.new(file: TOKEN_PATH)
    authorizer = Google::Auth::UserAuthorizer.new(client_id, SCOPE, token_store)
    user_id = 'default'
    credentials = authorizer.get_credentials(user_id)
    if credentials.nil?
      url = authorizer.get_authorization_url(base_url: OOB_URI)
      puts "Open the following URL in the browser and enter the resulting code after authorization:"
      puts url
      code = gets
      credentials = authorizer.get_and_store_credentials_from_code(user_id: user_id, code: code, base_url: OOB_URI)
    end
    credentials
  end

  def create_event
    event = Google::Apis::CalendarV3::Event.new(
      summary: @event_title,
      description: @event_description,
      start: {
        date_time: @start_time,
        time_zone: 'America/Los_Angeles',
      },
      end: {
        date_time: @end_time,
        time_zone: 'America/Los_Angeles',
      },
      attendees: @attendees
    )

    @service.insert_event(@calendar_id, event)
  end
end