require 'google_search'

# Description: Sublayer::Action responsible for performing a Google search and returning the top search results.
# This action integrates with the Google Search API (or a suitable gem wrapper).
#
# It is initialized with a search query and optionally the number of results to return.
# It returns an array of search results, each containing title, URL, and snippet.
#
# Example usage: When you want to gather information from the web based on a query generated by an LLM.

class GoogleSearchAction < Sublayer::Actions::Base
  def initialize(query:, num_results: 5)
    @query = query
    @num_results = num_results
    @api_key = ENV['GOOGLE_SEARCH_API_KEY']
    @cx = ENV['GOOGLE_SEARCH_ENGINE_ID'] # Custom Search Engine ID
  end

  def call
    begin
      search_results = perform_search
      Sublayer.configuration.logger.log(:info, "Successfully performed Google search for query: \#{@query}")
      search_results
    rescue GoogleSearch::Error => e
      error_message = "Error performing Google search: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    rescue StandardError => e
      error_message = "Error during Google search: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise e
    end
  end

  private

  def perform_search
    search = GoogleSearch.new(api_key: @api_key, cx: @cx)
    results = search.search(@query, num: @num_results)

    results.map do |result|
      {
        title: result.title,
        url: result.link,
        snippet: result.snippet
      }
    end
  end
end