require 'jira-ruby'

# Description: Sublayer::Action responsible for adding a comment to an existing Jira issue.
# This action allows for seamless integration with Jira, enabling you to keep issues updated
# with information generated by AI or other Sublayer Actions.
#
# Requires: 'jira-ruby' gem
# $ gem install jira-ruby
# Or add `gem 'jira-ruby'` to your Gemfile
#
# It is initialized with issue_key and comment_body. 
# It returns the ID of the created comment to confirm it was added successfully.
#
# Example usage: When you want to update a Jira issue with insights or data generated by an AI model.

class JiraAddCommentAction < Sublayer::Actions::Base
  def initialize(issue_key:, comment_body:)
    @issue_key = issue_key
    @comment_body = comment_body
    @client = JIRA::Client.new(
      username: ENV['JIRA_USERNAME'],
      password: ENV['JIRA_API_TOKEN'],
      site: ENV['JIRA_SITE'],
      context_path: '',
      auth_type: :basic
    )
  end

  def call
    begin
      comment = add_comment
      Sublayer.configuration.logger.log(:info, "Comment added successfully to Jira issue: #{@issue_key}")
      return comment.id
    rescue JIRA::HTTPError => e
      error_message = "Error adding comment to Jira issue: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    end
  end

  private

  def add_comment
    issue = @client.Issue.find(@issue_key)
    comment = issue.comments.build
    comment.save(body: @comment_body)
    return comment
  end
end