require 'jira-ruby'

# Description: Sublayer::Action responsible for retrieving all comments from a specific Jira issue.
# This action allows for integration with document generation workflows or sentiment analysis tasks.
#
# Requires: 'jira-ruby' gem
# $ gem install jira-ruby
# Or add `gem 'jira-ruby'` to your Gemfile
#
# It is initialized with the issue_key of the Jira issue.
# It returns an array of comments from the Jira issue.
#
# Example usage: When you want to collect comments from a Jira issue for sentiment analysis or
# to include in a document report generated by AI.

class JiraIssueCommentCollectorAction < Sublayer::Actions::Base
  def initialize(issue_key:)
    @issue_key = issue_key
    @client = JIRA::Client.new(
      username: ENV['JIRA_USERNAME'],
      password: ENV['JIRA_API_TOKEN'],
      site: ENV['JIRA_SITE'],
      context_path: '',
      auth_type: :basic
    )
  end

  def call
    begin
      issue = @client.Issue.find(@issue_key)
      comments = issue.comments.map(&:body)
      Sublayer.configuration.logger.log(:info, "Successfully retrieved comments for Jira issue #{@issue_key}")
      comments
    rescue JIRA::HTTPError => e
      error_message = "Error fetching Jira issue comments: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise StandardError, error_message
    rescue StandardError => e
      error_message = "Unexpected error: #{e.message}"
      Sublayer.configuration.logger.log(:error, error_message)
      raise e
    end
  end
end
