require 'google/apis/gmail_v1'

# Description: Sublayer::Action responsible for sending emails via the Gmail API.
# This action allows integration with Gmail for sending notifications or other email communications.
#
# It is initialized with recipient_email, subject, body, and optional attachments.
# It returns a success/failure status.
#
# Example usage: Sending notifications or reports generated by AI workflows.

class GmailSendEmailAction < Sublayer::Actions::Base
  def initialize(recipient_email:, subject:, body:, attachments: [])
    @recipient_email = recipient_email
    @subject = subject
    @body = body
    @attachments = attachments

    @gmail = Google::Apis::GmailV1::GmailService.new
    @gmail.authorization = Google::Auth.get_application_default(['https://www.googleapis.com/auth/gmail.send'])
  end

  def call
    begin
      message = build_message
      @gmail.send_user_message('me', message)

      Sublayer.configuration.logger.log(:info, "Email sent successfully to #{@recipient_email}")
      return true
    rescue StandardError => e
      Sublayer.configuration.logger.log(:error, "Error sending email: #{e.message}")
      return false
    end
  end

  private

  def build_message
    msg = Mail.new
    msg.to = @recipient_email
    msg.from = 'me'
    msg.subject = @subject
    msg.text_part = Mail::Part.new do
      body @body
    end

    @attachments.each do |attachment|
      msg.add_file(attachment)
    end

    msg_raw = msg.to_s
    Google::Apis::GmailV1::Message.new(raw: msg_raw.encode('ASCII-8BIT'))
  end
end