name: daily_action_suggestion_gemini

on:
  workflow_dispatch:
  schedule:
  - cron: '0 10 * * *'

jobs:
  daily_action_suggestion_gemini:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4.2.0
        with:
          repository: sublayerapp/sublayer
          path: sublayer
          fetch-depth: 0
      - name: Checkout Current Repository
        uses: actions/checkout@v4.2.0
        with:
          path: sublayer_actions
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install dependencies
        run: |
          gem install sublayer octokit
      - name: Run daily_action_suggestion_gemini
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: ruby sublayer_actions/.github/workflows/daily_action_suggestion/daily_action_suggestion_gemini.rb
