# Description: Sublayer::Action responsible for creating a new card on a Trello board.
# This action can be utilized to track AI-driven tasks or integrate with existing project management workflows via Trello.
#
# Requires: 'ruby-trello' gem
# $ gem install ruby-trello
# Or add `gem 'ruby-trello'` to your Gemfile
#
# It is initialized with a board_id, list_id, card_name, and optionally description, due_date, and labels.
# It returns the ID of the created card.
#
# Example usage: When you want to create a Trello card for tasks generated by an AI.

class TrelloCreateCardAction < Sublayer::Actions::Base
  require 'trello'

  def initialize(board_id:, list_id:, card_name:, description: nil, due_date: nil, labels: [])
    @board_id = board_id
    @list_id = list_id
    @card_name = card_name
    @description = description
    @due_date = due_date
    @labels = labels
    @client = Trello::Client.new(
      developer_public_key: ENV['TRELLO_DEVELOPER_PUBLIC_KEY'],
      member_token: ENV['TRELLO_MEMBER_TOKEN']
    )
  end

  def call
    create_card
  rescue Trello::Error => e
    error_message = "Error creating Trello card: #{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise StandardError, error_message
  rescue StandardError => e
    error_message = "General error in creating Trello card: #{e.message}"
    Sublayer.configuration.logger.log(:error, error_message)
    raise e
  end

  private

  def create_card
    list = @client.find(:list, @list_id)
    card = list.cards.create(
      name: @card_name,
      desc: @description,
      due: @due_date,
      labels: fetch_labels(@labels)
    )
    Sublayer.configuration.logger.log(:info, "Trello card created successfully with ID: #{card.id}")
    card.id
  end

  def fetch_labels(label_names)
    board = @client.find(:board, @board_id)
    board_labels = board.labels
    label_ids = board_labels.select { |label| label_names.include?(label.name) }.map(&:id)
  end
end